### ISSUE TITLE
BinaryWriteFailedException results in locked connection

### ISSUE THREAD

**Issue by zcargnop** [bytefish/PgBulkInsert#43] opened 2019-10-10 02:49 UTC
I am using your library and it works great for the most part. However, when the DB gets under heavy load I sometimes get a BinaryWriteFailedException 
```
Caused by: java.io.IOException: Ending write to copy failed.
        at org.postgresql.copy.PGCopyOutputStream.close(PGCopyOutputStream.java:107) ~[postgresql-42.2.6.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:161) ~[pgbulkinsert-3.4.jar:?]
        ... 11 more
Caused by: org.postgresql.util.PSQLException: Database connection failed when ending copy
        at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:997) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:45) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.copy.PGCopyOutputStream.endCopy(PGCopyOutputStream.java:168) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.copy.PGCopyOutputStream.close(PGCopyOutputStream.java:105) ~[postgresql-42.2.6.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:161) ~[pgbulkinsert-3.4.jar:?]
        ... 11 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823) ~[?:?]
        at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.core.PGStream.receiveChar(PGStream.java:321) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1107) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:993) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:45) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.copy.PGCopyOutputStream.endCopy(PGCopyOutputStream.java:168) ~[postgresql-42.2.6.jar:?]
        at org.postgresql.copy.PGCopyOutputStream.close(PGCopyOutputStream.java:105) ~[postgresql-42.2.6.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:161) ~[pgbulkinsert-3.4.jar:?]
```

At this point my application hangs and is not able to recover.  The code runs in a simple try catch block where if an exception is caught I call conn.rollback() then close the connection with conn.close() before calling a function to retry using a validated connection.  This is where the program hangs.  

```
daoWriter : inconsistent?
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	at java.lang.Object.wait(java.base@11.0.4/Object.java:328)
	at org.postgresql.core.v3.QueryExecutorImpl.waitOnLock(postgresql@42.2.6/QueryExecutorImpl.java:194)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(postgresql@42.2.6/QueryExecutorImpl.java:275)
	at org.postgresql.jdbc.PgStatement.executeInternal(postgresql@42.2.6/PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(postgresql@42.2.6/PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(postgresql@42.2.6/PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(postgresql@42.2.6/PgPreparedStatement.java:124)
	at org.postgresql.jdbc.PgConnection.isValid(postgresql@42.2.6/PgConnection.java:1377)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(com.zaxxer.hikari@3.3.1/PoolBase.java:156)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(com.zaxxer.hikari@3.3.1/HikariPool.java:185)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(com.zaxxer.hikari@3.3.1/HikariPool.java:161)
	at com.zaxxer.hikari.HikariDataSource.getConnection(com.zaxxer.hikari@3.3.1/HikariDataSource.java:100)
```

I'm using the Hikari connection pool and am wondering if I need to do something special when closing the connection after an exception? It seems like the connection is stuck in a locked state.  When an exception is thrown during copy is endCopy or cancelCopy called?

**Comment by bytefish** [comment] 2019-10-10 04:37
Yes indeed, if I read the Stacktrace correctly, there is an infinite wait in the ``QueryExecutorImpl.waitOnLock``, which causes the connection to time out at some point.

A quick search yielded this thread, which describes a similar problem:

* https://www.postgresql.org/message-id/CADGbXSQ--8pJcSPkC7%2BtR6rsGrk7p%3D141Bp16VJiOR5mg_SQpQ%40mail.gmail.com

It's a somewhat weird problem and I don't see a direct cause. I will continue looking for further information. As of now it looks like a JDBC driver problem, but it's possible I have misconfigured something.

There are also issues, which may be related to the problem... but Stacktraces don't really match:

* https://github.com/pgjdbc/pgjdbc/issues/194

**Comment by bytefish** [comment] 2019-10-10 04:45
Just as an idea... can you increase the ``sendBufferSize`` and ``recvBufferSize`` in the Connection String to a large value? People in the thread linked above mentioned some of the problems disappeared when increasinf these values.

The Connection String Parameters are described here:

* https://github.com/pgjdbc/pgjdbc#building-the-connection-url

**Comment by zcargnop** [comment] 2019-10-10 05:06
Thanks,
I will have a look at that and see if it helps.

**Comment by bytefish** [comment] 2019-10-10 05:09
Great, could you just give me some figures to know about the load? And are you reading from the database on the same thread / connection while writing the batched data? Just trying to replicate the error.

**Comment by zcargnop** [comment] 2019-10-10 05:37
I am using Hikari connection pool and each batch of inserts/updates is
processed via a single connection before the connection is closed so there
should be no reuse of connections except where the connection pool returns
the same connection to another process.We are seeing around 36k
transactions per second (tuples inserted/updated) at the database with a
ration of around 10 inserts per update. When an exception is caught during
COPY (insert) I close the connection and attempt to get a new connection
from the database and try a batch UPSERT. The issue is that whenever the
COPY fails (Caused by: java.net.SocketTimeoutException: Read timed out) the
application hangs when attempting to get a new connection from the pool.

**Comment by bytefish** [comment] 2019-10-10 05:39
Thanks for the details. I will try to reproduce the problem.

**Comment by bytefish** [comment] 2019-10-11 07:22
And does the error persist when increasing Buffer sizes?

**Comment by zcargnop** [comment] 2019-10-14 00:19
The last run worked without issue but it is not clear whether it was related to the send/receive buffer settings. The actual size of each batch is pretty random as it is based on a timeout period and max batch size.  For, previous runs I had left the timeout at 100ms (every 100ms we insert/update all data we've processed) with a max batch size of 10k.  This results in a lot of small batch COPY commands queueing up in the DB which I believe is what was causing the socket timeouts.  In the latest run I changed the configuration such that the max batch size was set to 40k with a 10second timeout.  The batch sizes still vary wildly (it is dependant on the incoming data being processed) however batch sizes were much larger with many batches reaching the 40k maximum.  I will try a few more tests to try and verify the root cause of the errors I was seeing previously and let you know if I find anything interesting.

**Comment by zcargnop** [comment] 2019-10-14 05:13
FYI, we did another run without setting send/receive buffer sizes and everything ran without issue suggesting that these settings did not impact processing.

**Comment by bytefish** [comment] 2019-10-14 05:13
@zcargnop Thanks for the effort you put into this. We leave this open, as long as we don't know the roor cause of the issue.

**Comment by zcargnop** [comment] 2019-10-25 01:19
it looks like the issue was related to the number of copy commands we were issuing. If the batch sizes are small (under 1000 records) and we issue them across multiple tables multiple times postgres seems to run into issues closing the connections and eventually the connections time out when new calls are made. We resolved this by increasing our batch sizes to 20,000-40,000 inserts per call.

**Comment by bytefish** [comment] 2019-10-25 07:14
Thanks for your valuable feedback, I really appreciate the effort you put into it.

I also thought about why the connections time out, but didn't have time to analyse it. If I remember correctly the COPY command should have the same locking like an INSERT statement, which means it is a RowExclusiveLock. This shouldn't lead to two connections blocking each other COPY statements.

I have found the following SQL statement to show the currently aquired locks. It's from a somewhat similiar issue in TimescaleDB (https://github.com/timescale/timescaledb/issues/158):

```sql
SELECT DISTINCT
    bl.pid AS blocked_pid,
    bl.usename AS blocked_user,
    bl.query AS blocked_query,
    bl.query_start AS blocked_query_start,
    relname AS blocked_on,
    lq.pid AS blocking_pid,
    lq.usename AS blocking_user,
    lq.query AS blocking_query,
    lq.query_start AS blocking_query_start,
    now(),
    pgl2.mode AS lock_type
FROM pg_stat_activity bl,
    pg_locks pgl1,
    pg_stat_activity lq,
    pg_locks pgl2,
    pg_class
WHERE bl.pid = pgl1.pid
    AND NOT pgl1.granted
    AND pg_class.oid = pgl1.relation
    AND pgl2.relation = pgl1.relation
    AND pgl2.granted
    AND lq.pid = pgl2.pid;
```

Maybe this also helps to debug the connections timing out.

**Comment by bytefish** [comment] 2019-10-31 08:20
@zcargnop Can we close the issue for now?

**Comment by zcargnop** [comment] 2019-10-31 09:45
Yes, thanks.

**Closed** 2019-10-31 10:05 UTC
Labels: bug, help wanted
